version: "2"
services:
    client:
        container_name: chatapp-client
        build: './client'
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:app
        links:
            - server
        networks:
            - chatappnetwork
    server:
        container_name: chatapp-server
        build: './server'
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./server:app
        depends_on:
            - mongodb
        networks:
            - chatappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - chatappnetwork
networks:
    chatappnetwork:
        driver: bridge
